### ISSUE TITLE
Error: Visualizer failed to load

### ISSUE THREAD

**Issue by Int32Overflow** [elmahio/ExceptionVisualizer#1]
![grafik](https://github.com/elmahio/ExceptionVisualizer/assets/20139038/f5ce2094-4358-4b7f-8be9-6e5a584f17fc)

**Comment by ThomasArdal** [comment]
How did you install the extension? Which version of Visual Studio do you use?

**Comment by ThomasArdal** [comment]
This is not something I can re-create. You can open a new issue with more details if this keeps happening.

**Comment by Mrsevic** [comment]
I also have this error bit with different contents:
![Untitled](https://github.com/elmahio/ExceptionVisualizer/assets/7526103/ff194e2a-15bd-4514-aa29-1e4c07528354)
