### ISSUE TITLE
How can i activate the extension?

### ISSUE THREAD

**Issue by Mrsevic** [elmahio/ExceptionVisualizer#2]
I cannot see how can I activate the extension? It'd be good to add some sample steps in readme

**Comment by ThomasArdal** [comment]
Good point. I'll add something to the readme. You can find it here:

![image](https://github.com/elmahio/ExceptionVisualizer/assets/563206/05aaca0a-ece5-4108-91c2-332f8e434646)

**Comment by ThomasArdal** [comment]
Thank you for the feedback. The screenshot has been added to the readme file too.

**Comment by Mrsevic** [comment]
I just discovered 🤦‍♂️. I thought there is an additional button.

Thanks
