### ISSUE TITLE
Error: Visualizer dependencies failed to load

### ISSUE THREAD

**Issue by Mrsevic** [elmahio/ExceptionVisualizer#3]
I have the error where visualizer fails to load with the following contents:

![Untitled](https://github.com/elmahio/ExceptionVisualizer/assets/7526103/cfed7f61-19cd-493c-a67b-bf7da2ecd434)

**Comment by ThomasArdal** [comment]
In the project you have open (the one causing an exception). Do you have `Newtonsoft.Json` installed? And if so, which version?

**Comment by Mrsevic** [comment]
Yes. Details:
Newtonsoft.Json" Version="13.0.3:

**Comment by ThomasArdal** [comment]
That's strange. There is a problem if you have a lower version installed but that is not the case here.

I'm hoping this is a Microsoft bug (like the lower version issue) so that it will get fixed in a newer VS. Which version are you using?

**Comment by Mrsevic** [comment]
Version 17.8.0. I have already deleted the MEF cache. I will try to update to the latest minor version.

**Comment by ThomasArdal** [comment]
I'm on 17.8.2 and haven't experienced it lately. I see that the newest one is 17.8.5.

**Comment by ThomasArdal** [comment]
@Mrsevic Do you still experience this issue?

**Comment by ThomasArdal** [comment]
I will close this one since I'm not able to replicate it.
